### ISSUE TITLE
some files doesn't exist

### ISSUE THREAD

**Issue by SeekPoint** [dongguosheng/SogouQTRelevance#1]
rzai@rzai00:~/prj/SogouQTRelevance$ bash run.sh 
01
Load Digit Dict Complete.
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.884 seconds.
Prefix dict has been built succesfully.
TOTAL_DOC: 38268
TOTAL_DOC: 38268
Begin to gen tfidf model ...
Begin to gen lsi model ...
Begin to gen lda model ...
Traceback (most recent call last):
  File "sogou.py", line 422, in <module>
    main()
  File "sogou.py", line 400, in main
    gen_topic_model(data_dir + 'data_for_tm.txt', with_label=True)
  File "sogou.py", line 74, in gen_topic_model
    dictionary.save('../model/topic_model/dict')
  File "/usr/local/lib/python2.7/dist-packages/gensim/utils.py", line 288, in save
    pickle(self, fname)
  File "/usr/local/lib/python2.7/dist-packages/gensim/utils.py", line 666, in pickle
    with smart_open(fname, 'wb') as fout: # 'b' for binary, needed on Windows
  File "/usr/local/lib/python2.7/dist-packages/gensim/utils.py", line 661, in smart_open
    return open(fname, mode)
IOError: [Errno 2] No such file or directory: '../model/topic_model/dict'
02

[+] General Parameters:
LETOR 4.0 dataset: No
Training data:	./data/train_feature
Ranking method:	MART
Feature description file:	Unspecified. All features will be used.
Train metric:	ERR@10
Test metric:	ERR@10
Highest relevance label (to compute ERR): 4
Feature normalization: No
Model file: ./model/model.txt

[+] MART's Parameters:
No. of trees: 50
No. of leaves: 10
No. of threshold candidates: 256
Learning rate: 0.1
Stop early: 100 rounds without performance gain on validation data

Error in FeatureManager::read(): java.io.FileNotFoundException: ./data/train_feature (No such file or directory)
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at ciir.umass.edu.learning.Evaluator.getFeatureFromSampleVector(Unknown Source)
	at ciir.umass.edu.learning.Evaluator.evaluate(Unknown Source)
	at ciir.umass.edu.learning.Evaluator.main(Unknown Source)

[+] General Parameters:
LETOR 4.0 dataset: No
Model file:	./model/model.txt
Feature normalization: No
Model:		MART
Error in FeatureManager::read(): java.io.FileNotFoundException: ./data/test_feature (No such file or directory)
03
paste: ./data/test_qid: No such file or directory
04
[0, 0, 0, 0]
rzai@rzai00:~/prj/SogouQTRelevance$

**Comment by dongguosheng** [comment]
try `mkdir -p model/topic_model` ?

**Comment by SeekPoint** [comment]
fixed some error reports

but where is  ./data/train_feature 

mldl@mldlUB1604:/media/mldl/data1t/os_prj/ykdebug_SogouQTRelevance$ bash run.sh 
01
Traceback (most recent call last):
  File "sogou.py", line 5, in <module>
    import jieba
ImportError: No module named jieba
02

[+] General Parameters:
LETOR 4.0 dataset: No
Training data:	./data/train_feature
Ranking method:	MART
Feature description file:	Unspecified. All features will be used.
Train metric:	ERR@10
Test metric:	ERR@10
Highest relevance label (to compute ERR): 4
Feature normalization: No
Model file: ./model/model.txt

[+] MART's Parameters:
No. of trees: 50
No. of leaves: 10
No. of threshold candidates: 256
Learning rate: 0.1
Stop early: 100 rounds without performance gain on validation data

Error in FeatureManager::read(): java.io.FileNotFoundException: ./data/train_feature (No such file or directory)
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at ciir.umass.edu.learning.Evaluator.getFeatureFromSampleVector(Unknown Source)
	at ciir.umass.edu.learning.Evaluator.evaluate(Unknown Source)
	at ciir.umass.edu.learning.Evaluator.main(Unknown Source)

[+] General Parameters:
LETOR 4.0 dataset: No
Model file:	./model/model.txt
Feature normalization: No
Model:		MART
Error in FeatureManager::read(): java.io.FileNotFoundException: ./data/test_feature (No such file or directory)
03
paste: ./data/test_qid: No such file or directory
04
[0, 0, 0, 0]
mldl@mldlUB1604:/media/mldl/data1t/os_prj/ykdebug_SogouQTRelevance$

**Comment by dongguosheng** [comment]
> `ImportError: No module named jieba`

`pip install jieba`
